Add controllers
IvanSuchilin/java-shareit pull request #1
Opened 2022-11-28 18:52 UTC by IvanSuchilin

2022-11-30 17:30 UTC, Fleaman777 requested changes

2022-11-30 17:30 UTC, Fleaman777 commented on pom.xml
> +			</plugin><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><configuration><source>8</source><target>8</target></configuration></plugin>
отформатируй эту строчку, а то она слегка выделяется на фоне остальных

2022-11-30 17:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestHeader("X-Sharer-User-Id") Long userId, @RequestBody ItemDto itemDto) {
X-Sharer-User-Id - можно было бы вынести в константу

2022-11-30 17:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Обновлеие данных вещи {}", itemDto.getName());
маленькая опечатка "Обновлние"

2022-11-30 17:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public boolean equals(Object o) {
метод equals - можно сделать через аннотацию

2022-11-30 17:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        log.debug("Получен запрос POST /items");
не очень хороший лог, т.к. метод create может быть использован другими сервисами напрямую, 
в таком случае лог будет немного вводить в заблуждение. т.к. POST запроса  не будет, а лог выведется

аналагично в похожих местах

2022-11-30 17:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        return itemStorage.getAllOwnerItems(userId).stream().map(itemMapper::toDTO).collect(Collectors.toList());
стрим лучше воспринимается в стрим формате

2022-11-30 17:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +        return allItems;
хороший метод что бы сделать его через стрим

2022-11-30 17:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +                .collect(Collectors.toList());
можно не собирать в лист, а сразу выполнять логику которая в return

2022-11-30 17:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/validator/UserDtoValidator.java
> +            log.error("Адрес электронной должен содержать символ @");
дело вкуса, 
но мне кажется, валидации больше подходит уровень логирования warn,
т.к. error больше означает, что случилось что-то, с чем приоложение не будет работать в штатном реджиме,
warn - случилось что-то непредвиденное, но не критичное, что нормально обрабатывается

2022-12-01 13:08 UTC, IvanSuchilin commented on pom.xml
> +			</plugin><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><configuration><source>8</source><target>8</target></configuration></plugin>
done

2022-12-01 13:11 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestHeader("X-Sharer-User-Id") Long userId, @RequestBody ItemDto itemDto) {
done

2022-12-01 13:12 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Обновлеие данных вещи {}", itemDto.getName());
done

2022-12-01 13:23 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public boolean equals(Object o) {
done

2022-12-01 13:29 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        log.debug("Получен запрос POST /items");
done

2022-12-01 13:32 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        return itemStorage.getAllOwnerItems(userId).stream().map(itemMapper::toDTO).collect(Collectors.toList());
done

2022-12-01 13:48 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +                .collect(Collectors.toList());
done

2022-12-01 13:54 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/user/validator/UserDtoValidator.java
> +            log.error("Адрес электронной должен содержать символ @");
Учту, спасибо! Изменил

2022-12-02 10:03 UTC, Fleaman777 approved these changes

2022-12-02 10:03 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        log.debug("Получен на создание вещи {}", itemDto.getName());
можно просто "создание вещи...." )

2022-12-02 10:03 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +                .collect(Collectors.toList());
супер, совсем другой разговор

2022-12-02 10:03 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +                .collect(Collectors.toList());
супер

2022-12-10 16:17 UTC, merged