Add bookings
IvanSuchilin/java-shareit pull request #2
Opened 2022-12-21 18:59 UTC by IvanSuchilin

2022-12-22 16:29 UTC, Fleaman777 requested changes

2022-12-22 16:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                             @RequestParam(name = "approved") Boolean approved) {
можно в аннотации не указывать параметр name, если его значение совпадает с названием аргумента в методе

2022-12-22 16:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/mappers/BookingMapper.java
> +}
здорово, хороший подход маппинга

2022-12-22 16:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +                bookings = bookingRepository.findCurrentByOwnerItems(ownerStored, LocalDateTime.now());
LocalDateTime.now() можно было бы вынести в локальную перменную

2022-12-22 16:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/validator/BookingValidator.java
> +public class BookingValidator {
молодец, правильный подход, с выносом валидации в отдельный компонент

2022-12-22 16:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @Column(name = "created")
по идеи, можно не указыыать аннотацию, если название поля совпадает с тем, что есть в бд

2022-12-22 16:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
>  }
если не используется, можно удалить, 
тем более спринг бин, хоть немного, но занимает место в приложении

2022-12-22 19:11 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                             @RequestParam(name = "approved") Boolean approved) {
Принял)

2022-12-22 19:27 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +                bookings = bookingRepository.findCurrentByOwnerItems(ownerStored, LocalDateTime.now());
Сделал

2022-12-22 19:36 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
>  }
Сделал + UserREpositoryImpl удалил

2022-12-22 19:37 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @Column(name = "created")
Принял, но добавил nullable = false в аннотацию

2022-12-23 16:32 UTC, Fleaman777 approved these changes

2022-12-26 14:28 UTC, merged