Add item requests
IvanSuchilin/java-shareit pull request #3
Opened 2023-01-09 15:19 UTC by IvanSuchilin

тесты c Query репозитория для booking не писал так как по сути эти же тесты реализовал в сервисных тестах с entity manager

2023-01-10 15:15 UTC, Fleaman777 requested changes

2023-01-10 15:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        final Pageable pageable = PageRequest.of((from / size), size, sort);
получение Pageable можно было бы вынести в общией метод

2023-01-10 15:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true, mappedBy = "item")
fetch = FetchType.EAGER - не всегда такой фетч тайп хорошо применять к зависимостям OneToMany, 
могут возникнуть проблемы с производительностью: при получении айтема сразу будут подтягиваться все его комментарии, даже если мы их не запрашиваем

возможно, больше бы подошло Lazy

2023-01-10 15:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +        List<ItemRequest> itemRequests = itemRequestRepository.findAllByRequesterIdOrderByCreatedDesc(userId);
можно было бы не создавать доп объект itemRequests, а сразу на  результате itemRequestRepository.findAllByRequesterIdOrderByCreatedDesc(userId) делать стрим

2023-01-10 15:15 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    LocalDateTime endBooking;
в тестах тоже хорошо бы придерживаться инкапсуляции и делать поля private

2023-01-10 15:15 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    }
хороший метод setUp, делаем все необходимое перед стартом тестов

2023-01-10 15:15 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceIntTest.java
> +    @Sql(scripts = {"file:dbTest/scripts/schemaTest.sql"})
более подходящее и ожидаемое место для хранения скрипта для тестовой бд было бы в пакете resources в test директории,

2023-01-10 15:15 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceIntTest.java
> +    @Sql(scripts = {"file:dbTest/scripts/schemaTest.sql"})
эту аннотацию можно было бы сразу применить на уровне класса, что бы не дубдировать ее над каждым тест методом

2023-01-10 15:15 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/request/service/ItemRequestServiceIntTest.java
> +    @Sql(scripts = {"file:dbTest/scripts/schemaTest.sql"})
аналагично с предыдущими 2 комментариями

2023-01-10 19:38 UTC, IvanSuchilin commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceIntTest.java
> +    @Sql(scripts = {"file:dbTest/scripts/schemaTest.sql"})
Done

2023-01-10 19:39 UTC, IvanSuchilin commented on src/test/java/ru/practicum/shareit/request/service/ItemRequestServiceIntTest.java
> +    @Sql(scripts = {"file:dbTest/scripts/schemaTest.sql"})
Done

2023-01-10 19:39 UTC, IvanSuchilin commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceIntTest.java
> +    @Sql(scripts = {"file:dbTest/scripts/schemaTest.sql"})
Done

2023-01-10 19:40 UTC, IvanSuchilin commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    LocalDateTime endBooking;
Done

2023-01-10 19:43 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +        List<ItemRequest> itemRequests = itemRequestRepository.findAllByRequesterIdOrderByCreatedDesc(userId);
Done

2023-01-10 19:56 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        final Pageable pageable = PageRequest.of((from / size), size, sort);
done

2023-01-10 20:21 UTC, IvanSuchilin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true, mappedBy = "item")
c Lazy у меня происходил краш с "failed to lazily initialize a collection of role.."
Поэтому я и решил прибегнуть в рамках проекта к FetchType.EAGER

2023-01-11 17:22 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true, mappedBy = "item")
супер, молодец что разобрался!

2023-01-11 17:28 UTC, Fleaman777 approved these changes

2023-01-11 17:28 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    BookingRepository bookingRepository;
тоже можно пометить private

2023-01-11 17:28 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +}
тесты то, что нужно 👍

2023-01-11 19:22 UTC, merged